# Generated by Django 3.2 on 2021-09-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
